import {
    START_FORM_IMPORTANT,
    APPEARANCE_FORM_IMPORTANT,
    BASICS_FORM_IMPORTANT,
    DEEN_FORM_IMPORTANT,
    FINISH_FORM_IMPORTANT,
    PROFESSION_FORM_IMPORTANT,
    FAMILY_RELATIONS_FORM_IMPORTANT,
    FRIENDSHIPS_FORM_IMPORTANT,
    LIFESTYLE_FORM_IMPORTANT,
} from "../actions/types";
const user = JSON.parse(localStorage.getItem("user"));
const initialState = {
    phone: false,
    purpose: false,
    gender: false,
    birthdate: false,
    followingforspouse: false,
    WhattypeandlevelofIslamicstudyingwouldyouwantamarriagematchtohavecompleted: false,
    TheIslamicteachingssectthatyoufollow: false,
    Whichscholarsdoyoutakeknowledgefrom: false,
    AreyoucurrentlystudyingIslamorhaveyouinthepastDoyouhavetheintentiontostudyIslamicstudiesinthefutureIfyestoanyofthesequestionspleaseprovidedetails: false,
    Howmanyofthe5prayersadaydoyouusuallyprayinthemasjid: false,
    DoyoumakeduaTOtheProphetSAWorduatopirsorsaintsthereisstrongevidencethatthistypeofduaissinfulshirk: false,
    DoyouwanttomakehijraonedayinshaAllah: false,
    DoyouvoluntaryFast: false,
    CanyoureadandorunderstandanyArabic: false,
    DoyoureadQuran: false,
    MemorizedanyQuranifsohowmuch: false,
    Whatstyleofmensclothingwouldyoupreferyourfuturehusbandwearwhenaroundnonmahramswhengoingtotheshoporatworketc: false,
    Whatstyleofwomensclothingwouldyoupreferyourfuturewifetowearwhenaroundnonmahramswhengoingtotheshoporparketc: false,
    Whichbeardstylemeetyourpreferences: false,
    Doyouwantawifewhowearsmakeupinfrontofnonmahrams: false,
    DoyoueatharamdrinkalcoholsmokecigarettessmokeshishaoruseecigarettesSelectallthatapply: false,
    Doyoufreemixwithnonmahramfemales: false,
    Doyoufreemixwithnonmahrammen: false,
    Typeofclothingworninfrontofnonmahrammenwhengoingtotheshopworkorparketc: false,
    Typeofclothingworninfrontofnonmahramwomanwhengoingtotheshoporworketc: false,
    DoyouwatchTV: false,
    DoyoulistentoMusic: false,
    Doyouwearmakeupinfrontofnonmahrams: false,
    youngestageyouarelookingfor: false,
    oldestageyouarelookingfor: false,
    Whattypeofhijabmatcheswithwhatyourelookingforinawife: false,
    WouldyouconsidermarragetoaMuslimawhodoesnotwearNiqaab: false,
    Whichmaritalstatusmatchwithwhatyouarelookingformen: false,
    Whichmaritalstatusmatchwithwhatyouarelookingforwomen: false,
    Wouldyouconsidermarryingsomeonewhoisalreadymarried: false,
    Wouldyoumarrysomeonewhoalreadyhaschildren: false,
    Wouldyoumarrysomeonewhohadmentalhealthproblems: false,
    Wouldyoumarrysomeonewhohadphysicaldisabilities: false,
    Whichcountrieswouldyoupreferyourmarriagepartnertoholdcitizenship: false,
    Doyouhavespecificrequirementswithregardstotheethnicityofafuturemarriagepartner: false,
    WhatisyourpreferencewhenitcomestomarryingaMuslimwhofoundIslamlateroninlife: false,
    Whichcountryorcountriesdoyoulivein: false,
    Whichcitytownvillagedoyoulivein: false,
    Whichcountryorcountriesdoyouholdcitizenship: false,
    Whatisyourmaritalstatusmen: false,
    Whatisyourmaritalstatuswomen: false,
    Doyouprayallofthe5dailyprayers: false,
    Doyoucoveryourhairfromnonmahrams: false,
    Whatareyourpreferredlivingarrangementsaftermarriage: false,
    Doyouhaveanyphysicaldisabilities: false,
    Doyouhaveanymentalhealthproblems: false,
    Doyouhaveanychildren: false,
    Doyouwantchildrenaftermarriage: false,
    Areyouwillingtorelocateaftermarriage: false,
    DidyourevertconverttoIslam: false,
    Whatistheshortestheightyoufindcompatible: false,
    Whatsthetallestheightyoufindcompatible: false,
    WhatisyourpreferencewhenitcomestothewaistsizeofyourfuturehusbandinshaAllahininches: false,
    Smallestdresssizethatmeetsyourrequirementsforawife: false,
    Largestdresssizethatmeetsyourrequirementsforawife: false,
    Whichbuildmatchesyourpreference: false,
    Whatisyourheight: false,
    Yourdresssize: false,
    Yourwaistsizeininches: false,
    Whichbuildbestdescribesyou: false,
    Whichstyleofbearddoyouhave: false,
    Whatisyourethnicity: false,
    Areyourfamilyreligious: false,
    WhatsectfollowingofIslamareyourfamilypractising: false,
    Howisyourrelationshipwithyourfamily: false,
    WhatmighttherelationshipbetweenyourfamilyandyournewmarriagepartnerbelikeinshaAllah: false,
    DoyouspendalotoftimewithfriendsWhatactivitiesdoyoudowithyourfriends: false,
    Areyourfriendsreligious: false,
    WhatsectfollowingofIslamdoyourfriendspractice: false,
    Howmightyourfriendsdescribeyourpersonality: false,
    Wouldyouwantyourfuturehusbandtofreemixwithyourfriends: false,
    Wouldyouwantyourfuturewifetofreemixwithyourfriends: false,
    Whichprofessionstatusdescribewhatyouwantyourfuturewifetohaveselectallthatapply: false,
    Whichprofessionstatusdescribewhatyouwantyourfuturehusbandtohaveselectallthatapply: false,
    Theminimumlevelofeducationyouwantyourmarriagepartnertohavecompleted: false,
    Whatisyourprofession: false,
    Whatisyourlevelofeducation: false,
    WhatdoyoubelievetheroleofthehusbandisWhatdoyoubelievetheroleofthewifeisandhowwouldyoufulfilyourrole: false,
    Isthereanyadditionalinformationyouwanttoaddaboutyourselforthemarriagepartneryouarelookingfor: false,
    suggestions: false,
    newsletter: false,
    user_id:user?._id
}
export default function (state = initialState, action) {
    const { type, payload } = action;
    switch (type) {
        case START_FORM_IMPORTANT:
            return {
                ...state,
                phone: payload.phone,
                purpose: payload.purpose,
                gender: payload.gender,
                birthdate: payload.birthdate

            };
        case APPEARANCE_FORM_IMPORTANT:
            return {
                ...state,
                Whatistheshortestheightyoufindcompatible: payload.Whatistheshortestheightyoufindcompatible,
                Whatsthetallestheightyoufindcompatible: payload.Whatsthetallestheightyoufindcompatible,
                WhatisyourpreferencewhenitcomestothewaistsizeofyourfuturehusbandinshaAllahininches: payload.WhatisyourpreferencewhenitcomestothewaistsizeofyourfuturehusbandinshaAllahininches,
                Smallestdresssizethatmeetsyourrequirementsforawife: payload.Smallestdresssizethatmeetsyourrequirementsforawife,
                Largestdresssizethatmeetsyourrequirementsforawife: payload.Largestdresssizethatmeetsyourrequirementsforawife,
                Whichbuildmatchesyourpreference: payload.Whichbuildmatchesyourpreference,
                Whatisyourheight: payload.Whatisyourheight,
                Yourdresssize: payload.Yourdresssize,
                Yourwaistsizeininches: payload.Yourwaistsizeininches,
                Whichbuildbestdescribesyou: payload.Whichbuildbestdescribesyou,
                Whichstyleofbearddoyouhave: payload.Whichstyleofbearddoyouhave,
                Whatisyourethnicity: payload.Whatisyourethnicity,
            };
        case BASICS_FORM_IMPORTANT:
            return {
                ...state,
                youngestageyouarelookingfor: payload.youngestageyouarelookingfor,
                oldestageyouarelookingfor: payload.oldestageyouarelookingfor,
                Whattypeofhijabmatcheswithwhatyourelookingforinawife: payload.Whattypeofhijabmatcheswithwhatyourelookingforinawife,
                WouldyouconsidermarragetoaMuslimawhodoesnotwearNiqaab: payload.WouldyouconsidermarragetoaMuslimawhodoesnotwearNiqaab,
                Whichmaritalstatusmatchwithwhatyouarelookingformen: payload.Whichmaritalstatusmatchwithwhatyouarelookingformen,
                Whichmaritalstatusmatchwithwhatyouarelookingforwomen: payload.Whichmaritalstatusmatchwithwhatyouarelookingforwomen,
                Wouldyouconsidermarryingsomeonewhoisalreadymarried: payload.Wouldyouconsidermarryingsomeonewhoisalreadymarried,
                Wouldyoumarrysomeonewhoalreadyhaschildren: payload.Wouldyoumarrysomeonewhoalreadyhaschildren,
                Wouldyoumarrysomeonewhohadmentalhealthproblems: payload.Wouldyoumarrysomeonewhohadmentalhealthproblems,
                Wouldyoumarrysomeonewhohadphysicaldisabilities: payload.Wouldyoumarrysomeonewhohadphysicaldisabilities,
                Whichcountrieswouldyoupreferyourmarriagepartnertoholdcitizenship: payload.Whichcountrieswouldyoupreferyourmarriagepartnertoholdcitizenship,
                Doyouhavespecificrequirementswithregardstotheethnicityofafuturemarriagepartner: payload.Doyouhavespecificrequirementswithregardstotheethnicityofafuturemarriagepartner,
                WhatisyourpreferencewhenitcomestomarryingaMuslimwhofoundIslamlateroninlife: payload.WhatisyourpreferencewhenitcomestomarryingaMuslimwhofoundIslamlateroninlife,
                Whichcountryorcountriesdoyoulivein: payload.Whichcountryorcountriesdoyoulivein,
                Whichcitytownvillagedoyoulivein: payload.Whichcitytownvillagedoyoulivein,
                Whichcountryorcountriesdoyouholdcitizenship: payload.Whichcountryorcountriesdoyouholdcitizenship,
                Whatisyourmaritalstatusmen: payload.Whatisyourmaritalstatusmen,
                Whatisyourmaritalstatuswomen: payload.Whatisyourmaritalstatuswomen,
                Doyouprayallofthe5dailyprayers: payload.Doyouprayallofthe5dailyprayers,
                Doyoucoveryourhairfromnonmahrams: payload.Doyoucoveryourhairfromnonmahrams,
                Whatareyourpreferredlivingarrangementsaftermarriage: payload.Whatareyourpreferredlivingarrangementsaftermarriage,
                Doyouhaveanyphysicaldisabilities: payload.Doyouhaveanyphysicaldisabilities,
                Doyouhaveanymentalhealthproblems: payload.Doyouhaveanymentalhealthproblems,
                Doyouhaveanychildren: payload.Doyouhaveanychildren,
                Doyouwantchildrenaftermarriage: payload.Doyouwantchildrenaftermarriage,
                Areyouwillingtorelocateaftermarriage: payload.Areyouwillingtorelocateaftermarriage,
                DidyourevertconverttoIslam: payload.DidyourevertconverttoIslam
            };
        case DEEN_FORM_IMPORTANT:
            return {
                ...state,
                followingforspouse: payload.followingforspouse,
                WhattypeandlevelofIslamicstudyingwouldyouwantamarriagematchtohavecompleted: payload.WhattypeandlevelofIslamicstudyingwouldyouwantamarriagematchtohavecompleted,
                TheIslamicteachingssectthatyoufollow: payload.TheIslamicteachingssectthatyoufollow,
                Whichscholarsdoyoutakeknowledgefrom: payload.Whichscholarsdoyoutakeknowledgefrom,
                AreyoucurrentlystudyingIslamorhaveyouinthepastDoyouhavetheintentiontostudyIslamicstudiesinthefutureIfyestoanyofthesequestionspleaseprovidedetails: payload.AreyoucurrentlystudyingIslamorhaveyouinthepastDoyouhavetheintentiontostudyIslamicstudiesinthefutureIfyestoanyofthesequestionspleaseprovidedetails,
                Howmanyofthe5prayersadaydoyouusuallyprayinthemasjid: payload.Howmanyofthe5prayersadaydoyouusuallyprayinthemasjid,
                DoyoumakeduaTOtheProphetSAWorduatopirsorsaintsthereisstrongevidencethatthistypeofduaissinfulshirk: payload.DoyoumakeduaTOtheProphetSAWorduatopirsorsaintsthereisstrongevidencethatthistypeofduaissinfulshirk,
                DoyouwanttomakehijraonedayinshaAllah: payload.DoyouwanttomakehijraonedayinshaAllah,
                DoyouvoluntaryFast: payload.DoyouvoluntaryFast,
                CanyoureadandorunderstandanyArabic: payload.CanyoureadandorunderstandanyArabic,
                DoyoureadQuran: payload.DoyoureadQuran,
                MemorizedanyQuranifsohowmuch: payload.MemorizedanyQuranifsohowmuch,
            };
        case FINISH_FORM_IMPORTANT:
            return {
                ...state,
                WhatdoyoubelievetheroleofthehusbandisWhatdoyoubelievetheroleofthewifeisandhowwouldyoufulfilyourrole: payload.WhatdoyoubelievetheroleofthehusbandisWhatdoyoubelievetheroleofthewifeisandhowwouldyoufulfilyourrole,
                Isthereanyadditionalinformationyouwanttoaddaboutyourselforthemarriagepartneryouarelookingfor: payload.Isthereanyadditionalinformationyouwanttoaddaboutyourselforthemarriagepartneryouarelookingfor,
                suggestions: payload.suggestions,
                newsletter: payload.newsletter,
            };
        case PROFESSION_FORM_IMPORTANT:
            return {
                ...state,
                Whichprofessionstatusdescribewhatyouwantyourfuturewifetohaveselectallthatapply: payload.Whichprofessionstatusdescribewhatyouwantyourfuturewifetohaveselectallthatapply,
                Whichprofessionstatusdescribewhatyouwantyourfuturehusbandtohaveselectallthatapply: payload.Whichprofessionstatusdescribewhatyouwantyourfuturehusbandtohaveselectallthatapply,
                Theminimumlevelofeducationyouwantyourmarriagepartnertohavecompleted: payload.Theminimumlevelofeducationyouwantyourmarriagepartnertohavecompleted,
                Whatisyourprofession: payload.Whatisyourprofession,
                Whatisyourlevelofeducation: payload.Whatisyourlevelofeducation,
            };
        case FAMILY_RELATIONS_FORM_IMPORTANT:
            return {
                ...state,
                Areyourfamilyreligious: payload.Areyourfamilyreligious,
                WhatsectfollowingofIslamareyourfamilypractising: payload.WhatsectfollowingofIslamareyourfamilypractising,
                Howisyourrelationshipwithyourfamily: payload.Howisyourrelationshipwithyourfamily,
                WhatmighttherelationshipbetweenyourfamilyandyournewmarriagepartnerbelikeinshaAllah: payload.WhatmighttherelationshipbetweenyourfamilyandyournewmarriagepartnerbelikeinshaAllah,
            };
        case FRIENDSHIPS_FORM_IMPORTANT:
            return {
                ...state,
                DoyouspendalotoftimewithfriendsWhatactivitiesdoyoudowithyourfriends: payload.DoyouspendalotoftimewithfriendsWhatactivitiesdoyoudowithyourfriends,
                Areyourfriendsreligious: payload.Areyourfriendsreligious,
                WhatsectfollowingofIslamdoyourfriendspractice: payload.WhatsectfollowingofIslamdoyourfriendspractice,
                Howmightyourfriendsdescribeyourpersonality: payload.Howmightyourfriendsdescribeyourpersonality,
                Wouldyouwantyourfuturehusbandtofreemixwithyourfriends: payload.Wouldyouwantyourfuturehusbandtofreemixwithyourfriends,
                Wouldyouwantyourfuturewifetofreemixwithyourfriends: payload.Wouldyouwantyourfuturewifetofreemixwithyourfriends,
            };
        case LIFESTYLE_FORM_IMPORTANT:
            return {
                ...state,
                Whatstyleofmensclothingwouldyoupreferyourfuturehusbandwearwhenaroundnonmahramswhengoingtotheshoporatworketc: payload.Whatstyleofmensclothingwouldyoupreferyourfuturehusbandwearwhenaroundnonmahramswhengoingtotheshoporatworketc,
                Whatstyleofwomensclothingwouldyoupreferyourfuturewifetowearwhenaroundnonmahramswhengoingtotheshoporparketc: payload.Whatstyleofwomensclothingwouldyoupreferyourfuturewifetowearwhenaroundnonmahramswhengoingtotheshoporparketc,
                Whichbeardstylemeetyourpreferences: payload.Whichbeardstylemeetyourpreferences,
                Doyouwantawifewhowearsmakeupinfrontofnonmahrams: payload.Doyouwantawifewhowearsmakeupinfrontofnonmahrams,
                DoyoueatharamdrinkalcoholsmokecigarettessmokeshishaoruseecigarettesSelectallthatapply: payload.DoyoueatharamdrinkalcoholsmokecigarettessmokeshishaoruseecigarettesSelectallthatapply,
                Doyoufreemixwithnonmahramfemales: payload.Doyoufreemixwithnonmahramfemales,
                Doyoufreemixwithnonmahrammen: payload.Doyoufreemixwithnonmahrammen,
                Typeofclothingworninfrontofnonmahrammenwhengoingtotheshopworkorparketc: payload.Typeofclothingworninfrontofnonmahrammenwhengoingtotheshopworkorparketc,
                Typeofclothingworninfrontofnonmahramwomanwhengoingtotheshoporworketc: payload.Typeofclothingworninfrontofnonmahramwomanwhengoingtotheshoporworketc,
                DoyouwatchTV: payload.DoyouwatchTV,
                DoyoulistentoMusic: payload.DoyoulistentoMusic,
                Doyouwearmakeupinfrontofnonmahrams: payload.Doyouwearmakeupinfrontofnonmahrams,
            };
        default:
            return state;
    }
}